# Generated by Django 4.0.1 on 2022-01-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
